version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+-rc.*$/
            branches:
              ignore: /.*/
      - release_rc:
          context: Production
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+-rc.*$/
            branches:
              ignore: /.*/
      - deploy:
          context: Production
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}

      - run: sudo npm install -g npm
      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}

      - run:
          name: run tests incl coverage
          command: npm run test
      - run: npm run lint
      - run: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths: .

  release_rc:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}

      - run: sudo npm install -g npm
      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}

      - run:
          name: run tests incl coverage
          command: npm run test
      - run: npm run lint
      - run: npm run build

      - run:
          name: git config
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "no-reply@civic.com"
            git config user.name "CI Deployer"
            git config --global push.default simple

      - run:
          name: version
          command: npm version patch --git-tag-version false

      - run:
          name: tag
          command: npm run tag  
  deploy:
    <<: *defaults  
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$IDENTITY_NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --access=public